### ISSUE TITLE
Problem installing via npm

### ISSUE THREAD

**Issue by sebkur** [derhuerst/vbb-cli#11]
I just installed vbb-cli locally via npm and when I try to run it:

    ./.bin/vbb-dep

I get this:

    ~/node_modules/vbb-cli/lib/product-symbol.js:6
    for (let p of hafas.profile.products) products[p.id] = p

    TypeError: Cannot read property 'products' of undefined
    at Object.<anonymous> (/home/z/node_modules/vbb-cli/lib/product-symbol.js:6:29)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/z/node_modules/vbb-cli/dep.js:11:23)
    at Module._compile (internal/modules/cjs/loader.js:688:30)

**Comment by sebkur** [comment]
node version is 10.14.1
npm version is 6.4.1

**Comment by derhuerst** [comment]
> I just installed vbb-cli locally via npm and when I try to run it:
>
> ```shell
> ./.bin/vbb-dep
> ```

How do this work? npm puts executables into `node_modules/.bin/vbb-dep`. Did you `cd` into `node_modules`?

> I get this:
>
> ```
> ~/node_modules/vbb-cli/lib/product-symbol.js:6
> for (let p of hafas.profile.products) products[p.id] = p
>
> TypeError: Cannot read property 'products' of undefined
> ```

Will look into it. Sounds like a bug.

**Comment by derhuerst** [comment]
Thanks for reporting. Published as `vbb-cli@1.0.1`.

Please run `npm update vbb-cli`; Please reopen if you continue to have issues.

**Comment by sebkur** [comment]
Yes, I `cd`ed into node_modules... Thanks for fixing!
