### ISSUE TITLE
vbb-dep problem

### ISSUE THREAD

**Issue by phlind** [derhuerst/vbb-cli#6]
First of all: awesome programm. Thanks for making it. The `vbb-route` command works very well for me, but whenever I try the `vbb-dep` command, I get this error:

```
module.js:491
    throw err;
    ^

Error: Cannot find module 'location'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/vbb-cli/dep.js:8:19)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

**Comment by derhuerst** [comment]
Thanks, fixed it. Will publish `0.6.0` now.
